name: flutter_image_map
version: 0.2.0
description: Image map, just like what we have in html
dependencies:
  flutter:
    sdk: flutter
environment:
  sdk: '>=2.2.0 <3.0.0'
repository: https://github.com/itzMeerkat/flutter_image_map

